sonar.projectKey=frontend
sonar.organization=devops-formation-15




# Fichiers à exclure
sonar.exclusions=**/*.test.js

# Rapport de couverture des tests (si disponible)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
